cquery-project/cquery

README.md
@jacobdufault Please take a look. These are a few suggested edits based on my experience setting up vscode + cquery.
(I'm not sure if this is the right way to make a pull request - it's my first one.)
=> Tweak readme file

src/command_line.cc
- error: lambda capture 'working_files' is not used
- error: lambda capture 'config' is not used
=> Update command_line.cc, fixes #14

src/threaded_queue.h
=> Add a virtual destructor for ThreadedQueue

.clang-format
=> Add project .clang-format

wscript
=> Fix wscript to support both Python 2 and Python 3

src/command_line.cc, src/language_server_api.cc, src/lex_utils.cc, src/match.cc, src/platform.cc, src/project.cc, src/query.cc, src/working_files.cc
=> Use indented TEST_SUITE ; update third party dependencies

emacs/lsp-cquery.el
Also some other small changes.
=> Add config cquery/executable and fix code lens

README.md
This is useful when building with cmake
=> Add note on compilationDatabaseDirectory option

wscript
Fixes https://github.com/jacobdufault/cquery/issues/41
=> Upgrade bundled llvm+clang to 5.0.0

src/command_line.cc
Hah, thats why it didnt show up. Might need some more customization
=> Emit semantic highlighting for types

vscode-client/package.json
https://github.com/jacobdufault/cquery/issues/125
=> [package.json] Add missing dependency "vscode"

src/clang_utils.cc
Before: diagnostic is a single-character range
After: it is a range.
=> Implement diagnostic range as per clang_formatDiagnostic

wscript
./waf build => build/app
./waf build_debug => build/debug/app
./waf build_release => build/release/app
`build` is deprecated and later on should be removed.
=> [waf] Add debug and release variants

src/clang_complete.cc, src/command_line.cc, src/indexer.cc, src/project.cc
Autocompletion works for a project as big as Instagram. However, finding references doesn't work most of the times.
=> Preliminary support for obj-c

wscript
The latest sparsepp and loguru build on FreeBSD:
https://github.com/greg7mdp/sparsepp/commit/605ebb953425b1cdd15d1f9d72c67ca2b57f6d43
https://github.com/emilk/loguru/commit/c3f5b432068effa566c5c8442a1a05fd794786e4
=> Update third_party dependencies to FreeBSD buildable versions

src/indexer.cc
```c++
#pragma clang diagnostic ignored "-Wdynamic-exception-spec"
void deprecated() throw(int);
void attribute() __attribute__((noreturn));
void noexcept0() noexcept;
struct A { void qualifier() const volatile __restrict; };
template <auto n> auto decltype0() -> decltype(n);
auto typeof0() -> __typeof(int);
```
=> [hover] Better heuristics to insert function name right before the paren pair enclosing parameters

src/clang_cursor.cc
Looks good on https://github.com/llvm-mirror/clang/blob/master/test/Index/parse-all-comments.c and some other test files.
@romix
=> Un-indent extracted comments

src/messages/text_document_completion.cc
If the text doesn't start with underscore, remove all candidates that start with underscore.
If found the exact text, remove all candidates that do not start with it.
=> Filter some completion results based on the input.

wscript
=> [waf] Fix --bundled-clang=5.0.1 on Mac OS X

src/clang_format.cc, src/clang_format.h, src/clang_utils.cc, src/clang_utils.h, src/ipc.cc, src/ipc.h, src/language_server_api.h, src/messages/text_document_formatting.cc, wscript
This implements document formatting. (#59)
=> [WIP] Document formatting

wscript
https://github.com/jacobdufault/cquery/issues/192
https://github.com/jacobdufault/cquery/issues/219
=> [waf] Add `test rax,rax` -> `test r8,r8` patch for --bundled-clang={4.0.0,5.0.1} on Linux

README.md
credit @HighCommander4 for https://github.com/jacobdufault/cquery/issues/216
=> Document the need to set cquery.launch.command

src/clang_translation_unit.cc, src/project.cc, src/test.cc
… that we do not need to strip main source filename from args
=> Use nullptr for main source filename in clang_parseTranslationUnit2FullArgv and rely on -working-directory for relative filename resolution

index_tests/objective-c/class.m, src/indexer.cc
=> Show errors of header file at the `include` position.

src/utils.cc
This function has a huge stack frame (> 8k, thanks to tinydir), and is
called recursively. I have seen this function causing some stack
overflows. So convert it to BFS to avoid that.
=> Convert GetFilesInFolderHelper to BFS

README.md
Also mention the "rainbow" feature and link to an article explaining it.
=> Mention semantic highlighting in the feature list

src/clang_format.cc
Adds some basic unit tests that exercise our document and range formatting logic.
(Requires compilation with `--use-clang-cxx`.)
=> Add unit tests for formatting documents and document ranges

src/utils.cc
=> Use @ as escape character of cache filenames

src/indexer.cc
Need better fix from @MaskRay.
=> Crash Hotfix.

.appveyor.yml, src/platform_win.cc, wscript
=> AppVeyor: Also build with clang from MSYS2

third_party/string_view.hpp, wscript
=> Fix compilation.

wscript
http://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/ignore-value.h
=> -Wno-unused-result on GCC

src/project.cc
=> Add dummy compiler argument.

cmake/DownloadAndExtractLLVM.cmake
Remove byte hacks + add correct url's for different clang versions + abort for unsupported combinations
=> CMake improvements 

src/fuzzy_match.cc
Fix the `Ranks("foo bar.h", {"foo/bar.h", "foobar.h"})` sorting issue.
It just requires some tuning of the parameters.
一個一直仰慕的學長聯繫我說cquery……雖然不開心但是再發一個合併申請吧
=> Improve fuzzy matching heuristics.

cmake/DownloadAndExtractLLVM.cmake
To use cmake as `cmake -H"$CQUERY" -B"$CQUERY/build"`.
=> Extract LLVM to specific directory.

src/utils.cc, src/utils.h
=> Make GetDirName return paths ending in '/'

CMakeLists.txt, cmake/FindClang.cmake
I forgot to add some commits to the last PR
=> convert Clang -> libclang for most of CMakeLists.txt

src/project.cc
This resolves #586 (albeit in a stupidly direct way; it's easy to imagine the desirability of at least a bit of configuration to be available).
=> Load from build/compile_commands.json

CMakeLists.txt
=> Copy clang and clang-format to output as cquery-clang and cquery-clang-format.

.appveyor.yml, .travis.yml, CMakeLists.txt, cmake/FindClang.cmake, src/clang_format.cc, src/project.cc, src/utils.cc, src/utils.h, wscript
Also install some additional folders so that cquery-clang resolves includes
correctly.
=> Use cquery-clang, cquery-clang-format.

src/messages/text_document_completion.cc
Unlike the previous approach, doesn't remove insertText so that clients that don't know about textEdit aren't affected. Clients that interpret textEdit incorrectly will still fail though...
=> Text edit for completions

src/messages/cquery_member_hierarchy.cc
=> fix error: no member named 'to_string'

src/project.cc
Sorry this took so long to get up. FWIW, most of the hacky patches in my branch have since dropped as they've been otherwise resolved 😄
=> Fixed typo '--dirver-mode'

CMakeLists.txt, src/clang_system_include_extractor.cc, src/compiler.cc, src/compiler.h, src/project.cc
=>  Preventing unrecognized flags passed to non Clang compiler

src/project.cc
Blacklist -march= and -Wl,-arch
=> [Fix #569] Blacklist arch flags

CMakeLists.txt, src/c_cpp_properties.cc, src/c_cpp_properties.h, src/project.cc
=> c_cpp_properties parsing

src/lsp.cc
The LSP specification currently lists two possible fields in the message header: "Content-Length" and "Content-Type"). The code in ReadJsonRpcContentFrom(...) does not recognize the latter and rejects messages that contain it. This patch allows the messages that contain it to be accepted.
=> Support Content-Type field in the message header

src/platform_win.cc
Fix windows compile issues after https://github.com/cquery-project/cquery/commit/5e602ab72037e1083ed223f3077d0bb486e4bc09
=> Fix windows header order

src/platform_posix.cc
=> Don't access an uninitialized optional

src/messages/text_document_definition.cc
=> List all possible overload resolutions when finding definitions
