cquery-project/cquery

src/command_line.cc, src/project.cc, wscript
@jacobdufault please take a look.
I don't have a way to test on Windows or Mac, so it's possible there are other warnings on those platforms and -Werror will break them. Nonetheless it seems like good discipline.
=> Fix compiler warnings and turn on warnings as errors

src/query.h
Adding this specialisation of std::hash fixes the build for me, I haven't investigated why the error occurred more deeply.
=> Fix build on macOS #20

emacs/lsp-cquery.el, emacs/lsp-mode-advice.el
Uses [lsp-mode](https://github.com/emacs-lsp/lsp-mode) to do completion, diagnostics, finding references, and eldoc (hover).
It also features experimental implementations of codeactions and semantic highlighting.
Currently its using a piece of lsp-mode, which is GPL, and therefore in a separate file. All other code is of course MIT
=> Emacs client

src/project.cc
This partially fixes https://github.com/jacobdufault/cquery/issues/42, where relative paths are not recognized. Now both `compile_commands.json`s generated by bear/cmake work on my laptop.
Note `clang_parseTranslationUnit2FullArgv` called in `src/clang_translation_unit.cc` does not accept main source filename in `args`.
The comparison `arg == result.filename` is still hacky because it does not work if the `"file"` attribute in `compile_commands.json` is different from the argument appearing in `"arguments`" or `"command"`.
When a source file in the project is a symlink to another directory, `platform_linux.cc:NormalizePath` should not call `realpath(3)` because it resolves symlinks and in this case resolving is not desired.
Note. `canonicalize_filename_mode (const char *name, …
=> Strip main source filename if it is a relative path in GetCompilationEntryFromCompileCommandEntry

wscript
This makes the python extension in vscode recognize it as a python file
=> Remove whitespace before shebang in wscript

vscode-client/build.cmd, vscode-client/build.py
This makes it easier to build the vscode plugin from windows or posix systems
=> Make build.cmd a python script

wscript
The combination of `-Wsign-compare` (brought by `-Wall`) and `-Werror` causes build failure when recent GCC (e.g. gcc 7) are used.
=> Use -Wno-sign-compare to make recent GCC happy

src/utils.cc
`filename` may be a directory (the latest Emacs lsp-mode sometimes sends a `textDocument/didOpen` message with an empty filename) or the file cannot be read. Note on Linux, a directory can be `open(2)`ed and the easiest way to catch this is to use a try catch.
There is some issue with the latest lsp-mode and it should be fixed.
The `querydb` thread should use a try ... catch ... because if it dies, the whole process dies. I am not familiar with the code base, but I think the check has its own merit.
=> Catch ios_base::failure exceptions in ReadContent

src/language_server_api.cc, src/language_server_api.h, src/working_files.cc
The wording in the protocol (https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_didChange) is "If range and rangeLength are omittted the new text is considered to be the full content of the document." Currently cquery replaces the full text when just rangeLength is omitted, but we could also compute the length here from the `end - start` to guard against lazy editors.
=> Only replace text if both rangeLength and range are not set

wscript
Using the option makes the assumption that `llvm-config` is in the path so that it can be probed for paths. I've tested it on Centos 7.2 with Clang 4.0.0 and it seems to work.
=> Added waf option to use clang from system (--use-system-clang)

emacs/cquery.el, src/command_line.cc, src/config.h
@topisani for the elisp, @jacobdufault for the C++
Also implements the `indexerCount` initialization option via a defcustom. Had it sitting in my index, figured I'd push it up.
=> Configurable EmitProgress methods

README.md, src/clang_translation_unit.cc, src/project.cc
so that we do not need to strip main source filename from args
Relevant lines in https://github.com/llvm-mirror/clang/blob/master/tools/libclang/CIndex.cpp :
```c++
// The 'source_filename' argument is optional.  If the caller does not
// specify it then it is assumed that the source file is specified
// in the actual argument list.
// Put the source file after command_line_args otherwise if '-x' flag is
// present it will be unused.
if (source_filename)
Args->push_back(source_filename);
```
This is a better fit than b0e46df0741497dd52598e7917758257d8350637 and it also likely fixes https://github.com/jacobdufault/cquery/issues/67
=> Specify nullptr for source_filename in clang_parseTranslationUnit2

src/command_line.cc
I experienced this hang problem when using cquery with
LanguageClient-neovim.
Sometimes std::cout would hang because the pipe is full, which would
normally be fine, since the client would read from the pipe soon.
However, in this case the client is blocking on a write(). This
shouldn't happen, because cquery has a stdin thread which constantly
reads from stdin. But, in C++, cin and cout are tied streams. Reading
from cin would cause cout to flush, which cause the read to block.
So, cquery can't write because the client doesn't read, the client won't
read before it finishes writing. It can't finish writing because cquery
can't read, and cquery can't read because cquery can't write. Which is a
deadlock.
The solution is to simply untie cin and cout.
=> Fix hang during reading from stdin

emacs/cquery.el, src/command_line.cc, src/indexer.cc, src/indexer.h, src/language_server_api.h, src/query.cc, src/query.h, src/serializer.cc
This allows hover strings to have syntax highlighting
Currently it breaks hover in vscode (with nothing logged), and makes emacs emit the infamous `(error No Content-Length header)`
=> Index file language and send it on hover

emacs/cquery.el
Old code action objects are now cleared (https://github.com/emacs-lsp/lsp-mode/commit/85442531315e826922362d0d545ddf9fc8653346), so the advice is no longer needed. 
Plus, the callback function for `codeAction` is a dynamically generated closure, so `lsp--text-document-code-action-callback` no longer exists.
=> Remove function advice around codeAction callback.

src/command_line.cc, src/indexer.cc, src/indexer.h, src/query.cc, src/serializer.cc
indexes `is_operator` for functions. Currently this is achieved by simply checking if `short_name` starts with `operator`, but there must be a better way, even though i searched the clang docs for a long time.
Also, i am not sure if its the best aproach to simply not highlight operators at all, but it looks a lot better:
Before, `operator==` was all yellow.
this fixes one part of #103
=> Don't highlight operators as functions

emacs/cquery.el, src/project.cc
Ran into these two issues while playing around with my config. With this patch:
1. `-include` directives in arg lists now resolve out properly. 
Before this patch:
`Creating completion session with arguments cc [SNIP] -I/home/josh/Upstream/linux/include/generated/uapi, -include, ./include/linux/kconfig.h, [SNIP]`
After:
``Creating completion session with arguments cc [SNIP] -I/home/josh/Upstream/linux/include/generated/uapi, -include, /home/josh/Upstream/linux/include/linux/kconfig.h, [SNIP]`
2. The `clang_resource_dir` supplied by cquery.el's  initParams would silently fail to do anything useful, littering diagnostics with "size_t is not defined" errors.
=> Ensure that paths passed to libclang are fully expanded

src/cache.cc, src/command_line.cc, src/utils.cc, src/utils.h
ext4's H(alfbaked B+) tree has a severe limitation: directory inode size never shrinks.
```
% stat -c 'inode size: %s' cquery_cached_index
inode size: 69632
% rm cquery_cached_index/*
% stat -c 'inode size: %s' cquery_cached_index
inode size: 69632
```
Flat cache directory makes it hard to delete files of a project, i.e. `rm cquery_cache/_your_project_*` may not work because it may exceed maximum argument length (`xargs --show-limits`, https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument https://www.in-ulm.de/~mascheck/various/argmax/)
With this commit, users can use `rm -r cquery_cache/_your_project/` to remove all cache files of a project.
Windows seems to use `/` for `"file"` attribute in `compile_commands.json`.
If you do not want …
=> Group cache files by projectRoot

src/clang_index.cc, src/clang_translation_unit.cc
Hopefully fixes https://github.com/jacobdufault/cquery/issues/43
`RegisterTarget` modifies a global variable `FirstTarget` which may be concurrently read by other threads that are calling `clang_createIndex`.
```
(gdb) bt                    
#0  0x00007fd5ac25d280 in llvm::TargetRegistry::RegisterTarget(llvm::Target&, char const*, char const*, bool (*)(llvm::Triple::ArchType), bool) ()
from /home/maskray/Dev/Util/cquery/build/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/lib/libclang.so.5
#1  0x00007fd5ab8fd5d8 in LLVMInitializeAArch64TargetInfo ()                                                      
from /home/maskray/Dev/Util/cquery/build/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/lib/libclang.so.5
#2  0x00007fd5aae90a86 in llvm::InitializeAllTargets() () …
```
=> Serialize clang_createIndex to prevent race condition (concurrent modify/read to FirstTarget defined in lib/Support/TargetRegistry.cpp)

src/clang_complete.cc
Cast the number to a char directly sometimes results in a invalid UTF-8
string, which is not good for some clients.
=> Convert priority to hex string for sortText

emacs/cquery.el
Example:
```elisp
(cquery-xref-find-locations-with-position "$cquery/derived")
```
=> [emacs] Add cquery-xref-find-locations-with-position

src/indexer.cc, src/utils.h
```diff
-    entry->dependencies.erase(std::find(
-        entry->dependencies.begin(), entry->dependencies.end(), entry->path));
+    entry->dependencies.erase(
+        std::remove(entry->dependencies.begin(), entry->dependencies.end(),
+                    entry->path),
+        entry->dependencies.end());
```
`a.erase(a.end())` is undefined behavior, but this is not an issue if `dependencies` is guaranteed to include `entry->path`. This is just safer.
`a.erase(a.end(), a.end()` is defined.
See http://en.cppreference.com/w/cpp/container/vector/erase
=> More idiomatic

src/language_server_api.cc
Add escapes for "#" and "," because buck build tool use them to differentiate target patterns in its generated compile_commands.json: [source](https://github.com/facebook/buck/blob/91ca77c2e44e494132075390a36ac16dd27a2dbb/src/com/facebook/buck/model/AbstractBuildTarget.java#L100-L111).
I considered covering the other cases from the [standard](http://www.ecma-international.org/ecma-262/6.0/#sec-uri-syntax-and-semantics), but decided against it because of the potential of extra string allocations if I add too many cases.
=> Escape more symbols in path handling.

src/serializer.cc
MarkedString::value is a mandatory field and the client may complain if `value` does not exist.
Emacs lsp-mode sometimes complains about `textDocument/hover` responses because `language` is non-empty but `value` is empty.
=> Reflect empty string

src/indexer.cc
For `#define foo 3`,
Before this commit, `detail_name` was `foo` (displayed for textDocument/hover reqeusts).
It is now shown as `#define foo 3`
=> [indexer] Change macro's IndexVar::def::detail_name to its approximate definition

wscript
WIP of https://github.com/jacobdufault/cquery/issues/84
Thank SJTUG organizer htfy96
=> [waf] Use RPATH $ORIGIN on FreeBSD/Linux and copy libclang.so.[4-9] to $PREFIX/lib/clang+llvm*/lib/

src/platform_linux.cc
IsSymlink was giving faulty results when finding recursive files on Linux. I've updated the function to use the built-in POSIX macro for checking if a file is a symlink.
https://linux.die.net/man/2/lstat
=> Fix IsSymLink on Linux

src/platform_posix.cc, wscript
This commit fixes issue on cquery's side. Its dependencies loguru and
sparsepp should also be ported to FreeBSD:
* https://github.com/emilk/loguru/pull/46
* sysinfo(2) called by sparsepp https://github.com/greg7mdp/sparsepp/blob/master/sparsepp/spp_memory.h#L32
With local hacks on loguru and sparsepp, it works on my FreeBSD 11.1
=> Support FreeBSD

src/query.h, src/query_utils.cc
```c
typedef int t;
#define m(_) t v
int main() {
m(a);  /// hover on `m` and call textDocument/definitions
}
```
Before: find `typedef int t;`
After: find `#define m(_) t v`
=> textDocument/definition: find macro definition instead of Type definition if the macro expands to tokens led by a SymbolKind::Type

src/indexer.cc
```c
#include <unistd.h>
int main() {
fsync(0); /// hover on `fsync`, invoke textDocument/definitions
}
```
Before: nothing happens
After: jump to fsync declaration in unistd.h
Note, a system header may be shared by different projects and currently the cache filename for it is the same for different projects. We may need to differentiate among projects.
The disk usage is not an issue. I don't see difference of cacheDirectory size before/after this commit.
```
du -sh /tmp/cquery
356K
```
=> [indexer] Index references to system headers

wscript
My target codebase requires clang 5.0, but didn't want to use the bundled 5.0 since it isn't recommended due to a bug.  So, I downloaded llvm trunk and built it myself and used it when building cquery via:
`./waf configure --variant=system --use-system-clang --llvm-config=/mydir/llvm-build/bin/llvm-config`
when running the resulting binary, though, i would get:
```
dyld: Library not loaded: @rpath/libclang.dylib
Referenced from: /Users/joel/git-3rd-party-repos/cquery/build/release/bin/cquery
Reason: image not found
Abort trap: 6
```
After reading up on `@rpath`, it seems we need to specify the `-rpath` when building a binary on mac, i.e. `rpath` has no system default like on linux/freebsd.  With this patch, everything works correctly for me, at least.
=> set rpath for mac when --use-system-clang

vscode-client/package.json, vscode-client/src/extension.ts
I have my `.vscode/settings.json` file checked into Git, because I have some project specific `"search.exclude"` and `"files.exclude"` settings there. The cquery extension adds `"cquery.cacheDirectory"` there with an absolute path, which results in conflicts when using the repository on different locations at the same time.
This will change the default to `'${workspaceFolder}/.vscode/cquery_cached_index/'` and replace the variable everytime the configuration is loaded. I've chosen `${workspaceFolder}` since that's what tasks.json also uses: https://code.visualstudio.com/docs/editor/tasks#_variable-substitution
=> Use ${workspaceFolder} instead of absolute path for cacheDirectory

src/indexer.cc, src/platform_posix.cc
struct A {
~A() {}
};
int main() {
A *a;
a->~A();   /// hover on `~`, call textDocument/definitions
}
Before: nothing happens
After: jump to `~A() {}`
=> [indexer] Treat explicit destructor call as not `is_implicit`

src/indexer.cc, tests/class.m
Tested with an instagram file. I was able to jump to name classes, properties, protocols, iVars, etc.
I was also able to jump to a system header (Foundation.h) and it creashed cquery because there are no write permissions on that folder, but I have an idea of how to fix that.
=> Support obj-c in the indexer

src/messages/text_document_hover.cc
`textDocument/hover` is usually called by editors whenever the cursor moves. For example, Emacs lsp-mode sets `eldoc-documentation-function` to `lsp--on-hover` which is invoked automatically. The error message is undesired.
=> For textDocument/hover, do not error on empty results

README.md, src/project.cc
- relative include path handling
- first line was being ignored if it was a flag (code assumed it was path to clang binary)
=> /.cquery file parsing fixes

src/clang_cursor.h, src/indexer.cc
```
namespace b{
namespace{
namespace a{
void e(); // Before a::e   After   b::(anon)::a::e
namespace{
namespace{
void f(); // Before: ::f  After: b::(anon)::a::(anon)::(anon)::f
}
}
}
}
}
```
=> [indexer] Handle unnamed namespaces

src/indexer.cc
`$cquery/base` could not locate overriden functions from template classes. This is caused by the lack of `         .template_specialization_to_template_definition()`.
```c++
template <class T>
struct B0 {
virtual void foo() {}
};
template <class T>
struct B1 {
virtual void bar() {}
};
template <>
struct B1<int> {
virtual void bar() {}
};
struct A : B0<int>, B1<int> {
// Before no action (a function named B0<int>::foo is instantiated but it does not have position info)
// After $cquery/base jumps to B0<T>::foo
void foo() override {}
// Before jumps to B1<int>::bar
// After same
void bar() override {}
};
```
=> [indexer] Make $cquery/base find correct overriden functions

src/clang_cursor.cc, src/command_line.cc
It uses a global variable `g_enable_comments` in `clang_cursor.cc` which should be placed somewhere else.
@romix 
`build/debug/bin/cquery --language-server --enable-comments`
=> Add experimental command line option --enable-comments to index comments and display them on textDocument/hover

libclang/CIndexDiagnostic.h, libclang/CIndexer.h, libclang/CLog.h, libclang/CXComment.h, libclang/CXCursor.h, libclang/CXIndexDataConsumer.h, libclang/CXLoadedDiagnostic.h, libclang/CXSourceLocation.h, libclang/CXString.h, libclang/CXTranslationUnit.h, libclang/CXType.h, libclang/CursorVisitor.h, libclang/Index_Internal.h, src/indexer.cc, src/indexer.h, src/type_printer.cc, src/type_printer.h, wscript
src/type_printer.cc demonstrates how to leverage clang C++ API
--use-clang-cxx   Use clang C++ API. They might be unstable and should be used with caution.
A copy of latest libclang/ in clang source tree is checked into libclang/ .
These header files are stable and provide some struct definitions used by clang-c/ header files.
=> Add --use-clang-cxx to waf and move type printer to src/type_printer.cc

src/clang_format.cc
Set the tab configuration (tab, spaces, amount) to the information
provided by the LSP client.
=> Default to Chromium's format style if cquery cannot obtain it

src/clang_format.cc
This fixes a bug when "style" does not have a value and we fallback to "predefined_style".
=> Fix format with predefined_style when a style cannot be obtained

src/platform_posix.cc
Other libc, for example, musl, doesn't have malloc_trim.
=> Check __GLIBC__ for malloc_trim instead of __linux__

src/project.cc
Reference:
1. https://clang.llvm.org/docs/UsersManual.html#differences-between-various-standard-modes
> If no -std option is specified, clang defaults to gnu11 mode.
2. https://gcc.gnu.org/onlinedocs/gcc/Standards.html
> The default, if no C language dialect options are given, is -std=gnu11.
=> Use gnu11 for C standard when none is specified

src/clang_complete.cc, src/working_files.cc, src/working_files.h
this is a crude, but empirically effective, attempt to fix https://github.com/jacobdufault/cquery/issues/228 and possibly https://github.com/jacobdufault/cquery/issues/32
=> freeze state of WorkingFiles to insulate them from async changes before shipping unsaved state off to clang

src/clang_cursor.cc
This strips an additional '/' at the end of comment:
```
/**
* name of the network
**/
std::string name() const { return name_; }
```
Before:
```
name of the network
/
```
After:
```
name of the network
```
=> [comments] Strip additional comment marker at the end of comments

src/project.cc
This does not return a boolean anymore, so it's misleading.
=> Delete wrong comment

src/utils.cc
clear break from noted commit; manifests itself if subdirectory tree has depth >1 in a project.
=> fix logic in GetFilesInFolderHelper from DFS-ification in 96f4ffc4b

wscript
This addresses a defect in c9c3cfb624fa2f55513955f82c579b9ca5240b52
=> Only shell out to llvm-config if the configure step found it

src/clang_format.cc, src/clang_utils.cc
This tests that the conversion between edits returned by `libFormat` and line/column ranges required by LSP clients is done correctly.
=> Add Clang replacements unit tests

.gitignore, src/messages/text_document_completion.cc
Fixing a bug where autocomplete results would be shown in Atom when typing `;` or even an empty space.
=> Fix autocompletion results on semicolon

src/import_pipeline.cc, src/indexer.cc
Otherwise these headers are marked in global file consumer and no other index files will be generated.
That `UpdateCachedModificationTime` seems to be not needed. Not sure about the `Reset` in the previous line.
=> Don't give up index files of headers if the .cc/.cpp file failed.

src/config.h, src/messages/text_document_completion.cc
#312.
Shell: `--init='{"filterAndSortCompletionResponse": false}'`.
Emacs: `(setq cquery-extra-init-params '(:filterAndSortCompletionResponse :json-false))`,
=> Add option to disable filtering and sorting completion response.

src/iindexer.cc, src/iindexer.h, src/import_pipeline.cc, src/indexer.cc, src/indexer.h, src/messages/initialize.cc, src/queue_manager.cc, src/queue_manager.h, src/test.cc
I think users should be aware of index errors before they post issues. It's also easier for developers to notice the problem rather than diving into the log file.
Cquery should have better index failure mechanism. For now, if bad thing happened, all files are already marked in global file consumer and no other indexes of them will be generated. Letting go the already generated index files is also not appropriate because they may have not gone through all the `on*` functions. I have also tried to unmark these files in global file consumer. But if the error occurs in a deep include file, almost all index attempts will fail. Any way, one failure should influence least the entire task. However, it does not appear to be easy nowadays.
=> Response on index error.

src/messages/cquery_call_tree.cc, src/query.cc, src/query.h
Instead of directly touching usr_to_{type,func_var}, use dedicated methods to touch them for a bit more abstraction around QueryDatabase.
=> Use GetQuery{Type,Func,Var}IdFromUsr for querying QueryDatabase::usr_to_{type,func_var}

.gitignore
This file is generated by vscode-client/build.py but is not checked in.
=> Add vscode-extension.vsix to .gitignore

src/indexer.cc
On Ubuntu 16.04 I get the following compile error in release mode:
../../src/indexer.cc: In function ‘ClangStorageClass {anonymous}::GetStorageClass(CX_StorageClass)’:
../../src/indexer.cc:130:1: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: all warnings being treated as errors
(I'm not sure if your standard is 'assert' in these cases, but there seemed be be a few other usages in the codebase)
=> Fix build on Ubuntu 16.04

src/message_handler.cc
Fixes #368 
@scturtle 
```c++
template <typename T>
struct vector {
T* begin();
};
template <typename T>
void foo(vector<T>& v) {
v.begin();    // The call of `begin` has an extent of `v.begin` (yes, the range includes undesired `v.`)
}
```
This makes the lambda -> `std::function` semantic hack fail.
=> Don't emit semantic highlight for operators or lambda

src/config.h, src/include_complete.cc, src/lex_utils.cc, src/lex_utils.h, src/messages/text_document_completion.cc
1. Set a default value of `includeCompletionWhitelistLiteralEnding`. Otherwise no header is found.
2. Only complete line that starts with `#include "` or `#include <`. So we can determine the last complete character.
3. Filter and sort the candidates without prefix `#include`.
=> Fix completion of headers.

src/utils.cc
28cd33e actually changed the behaviour of GetFilesInFolderHelper.
=> Fix #393 again.

src/platform_win.cc, src/project.cc, src/utils.cc, src/utils.h
Currently cquery only reads compiler arguments (.cquery) from project root. 
Under some circumstances (e.g. remote compiling), generating a compilation database with correct path in it is non-trivial, and allowing per directory compile arguments usually helps.
=>  Look for .cquery in any directory above the source file in the hierarchy.

src/messages/text_document_completion.cc
Since not everything is a reference, std::make_tuple() seems more appropriate than std::tie().
For heavy types, std::cref() can be used to preserve the reference.
=> refactor CompareLsCompletionItem

wscript
- Fixes wscript so symbolic link creation doesn't fail if Developer Mode is enabled
- Fixes arguments order to shutil.copy if symbolic link creation fails
- wscript now uses unicode version of CreateSymbolicLink (W suffix) and always passes unicode strings to that function
=> wscript fixes for Windows

src/include_complete.cc
Greetings, I have a folder with a ton of generated files I want to blacklist from include completion, so I would like  to check the directory for a match first before running the match against every file.
=> Match directory before looking at included files.

src/include_complete.cc, src/include_complete.h, src/language_server_api.h, src/lex_utils.cc
1. Each item has its default option between angle bracket and quote.
2. Better duplicate handling using include path instead of absolute path.
3. Make `documentation` optional to save json size.
4. Completion at `#include<cursor>` has a space after `include`.
=> Fix a bunch of stuffs in completion.

src/indexer.h
Instead of providing a specialization here, the preexisting macro can be used.
=> Use MAKE_ENUM_HASHABLE to hash SymbolKind

src/clang_complete.cc, src/clang_complete.h
As I was trying out cquery as a shared service I noticed some of the autocomplete requests were dropped.
This would be an issue because vscode-jsonrpc accumulates unresponded messages in a hash-table.
In the previous releases I've noticed ```TryEnsureDocumentParsed``` was taking the longest time in completequery.  From 368b266 onwards it seem to have improved significantly. So responding to all completion requests might not be a very expensive operation
=> Making completion_request_ ThreadedQueue from AtomicObject

src/project.cc
See https://github.com/cquery-project/cquery/issues/491
This pull request does not fix the wrongly formatted command printed when the libclang generic error happens. It just stops the error from happening.
=> Fix libclang generic error on Windows

CMakeLists.txt, cmake/DefaultCMakeBuildType.cmake, cmake/DownloadAndExtract7zip.cmake, cmake/DownloadAndExtractLLVM.cmake, cmake/FindClang.cmake
I've added a CMake implementation of the cquery build. This might not be a net advantage over Waf so I'll list some advantages and disadvantages I've found compared to Waf:
Advantages of CMake compared to Waf:
- Built-in support for finding many popular libraries (Using these usually leads to fewer bugs compared to writing the logic yourself)
- Ability to produce installers using CPack (not implemented yet but might be useful in the future)
- Ability to include non header-only C++ libraries with CMake support using add_subdirectory (gflags, glog, ...) which can be included as git submodules in the source tree
- Support for many generators (make/Ninja/MSBuild/...)
- (Subjective) Finding libraries in CMake is more robust compared to Waf
- More documentation/StackOverflow answers/tutorials …
=> Add CMake as alternative build system

src/project.cc
Apparently, people use [`-idirafter`](https://github.com/Valloric/ycmd/issues/874) too.
Note that this doesn't make an exhaustive list of include path flags, but it does make the list contain all the flags the users have encountered over the years, as far as ycmd is concerned.
=> Add -idirafter to kPathArgs

src/project.cc
As discussed with @MaskRay the clang CL driver detection isn't fool proof for two reasons.
- Windows' paths are case-insensitive.
- Multiple `--driver-mode` flags are allowed.
Some thing like `C:\\Program Files\\LLVM\\bin\\ClanG-Cl.eXe  --driver-mode=gcc --driver-mode=cl --driver-mode=gcc` does the following:
- `ClanG-Cl.eXe` implicitly means CL mode.
- `--driver-mode=gcc` overrides it and explicitly sets GCC mode.
- `--driver-mode=cl` overrides it and once again sets CL mode.
- `--driver-mode=gcc` finally sets the mode to GCC.
On the other hand, cquery right now does the following:
- `clang-cl` isn't found, so we are not in CL mode. - This is wrong.
- There's at least one `--driver-mode=cl` flag, so we definitely are in CL mode. - Once again wrong.
This PR changes the code to check the …
=> Make CL mode detection fool-proof

src/config.h, src/messages/text_document_did_change.cc, src/messages/text_document_did_save.cc
Like I mentioned in the gitter room, I wasn't able to put this to the test, though it looks like a straight forward way to do this.
Reason why there isn't a test for this is that I'm not sure how to make one.
The test would need to do the following:
- Index a file once.
- Make a change to that file.
- Make a change to the file, but not save it because we don't want to trigger reindexing on `didSave`.
- Fire a `textDocument/didChange` message.
- Reindex again.
- Assert the new index differs.
- Nothing to undo the change to the file, because the change shouldn't have been saved.
I'm just not sure how to make such a test for cquery.
Before this is marked `[READY]` let's consider turning off reindexing on `didSave` if we do it on `didChange`. From where I stand, the last `didChange` would …
=> [RFC] Conditionally allow reindex on didChange

src/messages/text_document_did_open.cc, src/project.cc, src/project.h
didOpen can override flags from compilation database.
didSave was able to reset the flags back.
This makes sure that the overridden flags persist.
Fixes #541
=> Make overridden flags persistent after didSave

src/messages/text_document_completion.cc
Current project's include directories usually appear in generated `compile_commands.json` as `-I`. These headers' `use_angle_brackets_` are inferred as `<`. The original filter makes it impossible to complete them with `"`.
PS: the design choice of fuzzy matcher makes `includesrc/timer.h` score higher than `includetimer.h` for text `inctimer` but I prefer the latter one.
=> Fix missing include completions.

src/project.cc
Fixes #544.
I'm not sure whether `/showIncludes` should also be included in that list, because cl.exe allow all flags to be passed with either `/` or `-`.
=> Ignore cl's -showIncludes

cmake/FindClang.cmake
We don't support downloading Clang 4.0 anymore and I think -print-resource-dir might give better diagnostics to solve #550. This implies using Clang 4.0 from system won't be possible anymore.
=> Switch to -print-resource-dir (drop support for system clang 4.0)

src/project.cc
System include paths that point to framework directories should be added
with -iframework instead of -isystem.
=> [READY] Use proper include flag for frameworks

src/messages/text_document_completion.cc, src/working_files.cc, src/working_files.h
Rather than just inserting text for completions, use textEdit to insert
text which replaces the entire identifier, including text after the
cursor.
=> Use textEdit for completions

CMakeLists.txt
=> Add stricter logic for checking if MSVC style compiler flags are needed

src/include_complete.cc, src/lsp_completion.h, src/messages/text_document_code_action.cc, src/messages/text_document_completion.cc, src/working_files.cc, src/working_files.h
Rather than just inserting text for completions, use range to insert
text which replaces the entire identifier, including text after the
cursor.
Additionally, deprecates textEdit, and changes uses of textEdit to
uses of insertText + range.
Reland of #598, which keeps insertText and uses range instead of the
deprecated textEdit. This should keep non-compliant clients (that only
parse insertText) happy.
=> Use range for completions

src/lsp.cc
Output the escape sequence instead of the newline.
=> Fixed newlines in error message

src/include_complete.cc, src/lsp_completion.h, src/messages/text_document_code_action.cc, src/messages/text_document_completion.cc
This reverts commit 27db9f85dccc3ff4d4ac2eefab66dcb4f4b4c747.
"Range" is a vscode API property, not an LSP one.
=> Revert "Use range for completions"

CMakeLists.txt
`SYSTEM_CLANG` is more correct since we're starting to integrate with more than just libclang (clang-format, clang-resource-directory)
=> remove lib suffix from cmake options

wscript
Otherwise the following error is seen and cquery fails to build:
```
[16/89] Compiling src/clang_format.cc
../../src/clang_format.cc:9:10: fatal error: pugixml.hpp: No such file or directory
#include <pugixml.hpp>
^~~~~~~~~~~~~
compilation terminated.
Waf: Leaving directory `/home/alex/cquery/build/release'
Build failed
-> task in 'bin/cquery' failed with exit status 1 (run with -v to display more information)
```
=> Need to add pugixml to includes for clang_format.cc to compile

src/project.cc
as mentioned in https://github.com/cquery-project/cquery/issues/641 this is a less common form of the already handled `-idirafter`
=> add `include-directory-after` to `kPathArgs`

src/method.cc
Fix the following building error on macOS.
```
Undefined symbols for architecture x86_64:
"std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
doctest::String doctest::detail::stringifyBinaryExpr<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [13]>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, char const (&) [13]) in method.cc.1.o
ld: symbol(s) not found for architecture x86_64
```
See more at …
=> Fix Building Error on macOS

src/project.cc
As mentioned in https://github.com/cquery-project/cquery/issues/641 this passes through additional flags that affect the output of `GetSystemIncludes()`.  It's likely some form of `-resource-dir` should also be passed, but that's for another day.
=> add additional flags to `kFlagsToPass` in `GetSystemIncludes`

src/utils.cc
We had an issue where a broken symlink caused the directory crawler to skip any other (valid) entries that were enumerated after the broken symlink.   This fix lets us skip that one file and soldier on through the rest in the directory.
=> continue directory listing even if broken symlink encountered

src/messages/cquery_call_hierarchy.cc, src/messages/cquery_inheritance_hierarchy.cc, src/messages/cquery_member_hierarchy.cc, src/messages/text_document_hover.cc, src/messages/workspace_execute_command.cc, src/serializer.h
The default json serializer omits std::optional fields that aren't
present, but LSP requires exactly one of |result| or |error| to be
present in every json rpc response.  This change fixes the responses of
cquery/{callHierarchy,inheritanceHierarchy,memberHierarchy} so they
always specify a |result| field, even when it's null.
Fixes #652.
=> Fix LSP json responses for some methods

src/config.h
dropOldRequests config was not added to Config::Completion in 
599e2f307bd823c734e582d00ed8fd22d5a53f1b
=> dropOldRequests config was not added to Config::Completion 

src/command_line.cc, src/lsp.cc, src/messages/text_document_definition.cc, src/method.cc, src/platform_posix.cc, src/platform_win.cc, src/project.cc
This fixed up all the warnings in the build on Windows using the MSVC from Visual Studio 15.7.1 (at least for the warnings displayed by default).
=> Fixed warnings

src/message_handler.cc
This resolves #675, where cquery would emit multiple `Bad index_line`
errors because it was trying to use `-1` as an index. The cause was
symbols found in a translation unit that weren't visibly present in
the file (e.g. expanded GoogleTest templated macros), and so had a
`start_line` of `-1`. The fix is to simply not publish a semantic
highlight for a symbol that cannot be highlighted.
=> Skip highlighting symbols not actually in file

third_party/tinydir.h
This brings in two MSVC fixes to TinyDir, one which extends
compatibility to before Windows 10 Anniversary Update, the other which
fixes an MSVC buffer overflow.
=> Update TinyDir to latest release, version 1.2.3

src/project.cc
These are MSVC flags that cause `clang-cl.exe` to crash, and are
unnecessary for cquery.
If the `/permissive` flag is present, it causes this error:
> clang-cl.exe: error: no such file or directory: '/permissive'
If any of the PCH flags are present, the following error occurs:
> error: input is not a PCH file
=> Blacklist MSVC `/permissive` and PCH compiler flags

src/messages/initialize.cc
`snippetSupport` is actually a std::optional, so if it exists and is false, `enableSnippets` remains true.  Fixes my comment in #657.
=> Fix enableSnippets setting in initialize message

src/project.cc
fix directory that contains generated file.  The dir shouldn't be set
to passed in arg after a temp directory is generated and created.
=> fix using compilationDatabaseCommand

src/config.h, src/messages/initialize.cc
Add a formatting.enabled (default true) config option to allow the
client to disable formatting. Additionally, only enable the formatting
provider if the client lists it in its capabilities.
=> Add config option for disabling formatting

wscript
Start printing a deprecation notice for Waf. I think we should also remove all links to the Waf page in the wiki as well (but leave the page itself intact until we actually remove the Waf build)
=> Deprecate Waf build

cmake/DownloadAndExtractClang.cmake
See #750 
Only use Ubuntu 16.04 on Ubuntu 16.04.
We could keep the 16.04 default but that means adding exceptions for every distro that doesn't work with the 16.04 archive which means extra maintenance burden. Since we didn't get any reports of issues with the 14.04 archive I think we're better off without that extra maintenance and defaulting to 14.04
=> Default back to Ubuntu 14.04 when downloading Clang

CMakeLists.txt
As [documented in MSDN](https://docs.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) this function requires Windows Vista or newer. While Visual Studio can't compile for XP anymore anyway,  Mingw-w64 still cares and won't define the function without the correctly set `_WIN32_WINNT` version.
~~Sorry about the removed trailing whitespaces, if you want I can clean that up so that my patch is only the one added line.~~
edit: `add_compile_definitions` -> `target_compile_definitions`
=> Set _WIN32_WINNT for SHGetKnownFolderPath

.appveyor.yml
Currently the matrix just executes the same build twice. This builds with MSYS2 again, but uses CMake instead of Waf. MSVC build is unchanged.
=> AppVeyor: Build with MSYS2 again

src/clang_indexer.cc, src/import_pipeline.cc, src/indexer.h, src/messages/cquery_file_info.cc, src/query.cc, src/query.h, src/serializer.cc, src/utils.cc, src/utils.h
On large projects where thousands of files each have thousands of arguments,
the args array of IndexFiles ends up causing cquery to run out of memory.
Currently the array is only used to check whether it can reload indices from cache,
so let it just store a hash and compare that instead of the full array.
=> Hash argument lists in IndexFiles

CMakeLists.txt
According to @jtalowell, `execinfo.h` is a glibc extension which doesn't exist in other C libraries.
This should allow compiling on different C libraries, but I don't have any to check.
If all goes well, this fixes #739
=> [READY] Check if execinfo.h exists

src/code_complete_cache.cc, src/code_complete_cache.h, src/import_pipeline.cc, src/import_pipeline.h, src/messages/initialize.cc
Should fix #754. Cached completions are still being used after indexing, so clearing them after indexing should cause it to do a full completion on the next call.
=> Clear code completion cache after indexing. Should fix #754

cmake/DownloadAndExtractClang.cmake
All system clang has been migrated to clang 7.0.0, but clang 6.0.0 for Darwin remains in `cmake/DownloadAndExtractClang.cmake`. and there is no hash file for clang 6.0.0/6.0.1, it will get an error when `cmake ..`
```
-- Using downloaded Clang
CMake Error at cmake/DownloadAndExtractClang.cmake:72 (message):
No SHA256 hash available for the current platform (Darwin) + clang version
(6.0.0) combination.  Please file an issue to get it added.
Call Stack (most recent call first):
CMakeLists.txt:94 (download_and_extract_clang)
```
=> Move to clang 7.0.0 for Darwin

src/platform.cc
Fixes https://github.com/cquery-project/cquery/issues/781 and https://github.com/cquery-project/cquery/issues/818.
=> Read stderr before stdout to fix gcc hang on Windows

src/c_cpp_properties.cc, src/clang_system_include_extractor.cc, src/clang_system_include_extractor.h, src/project.cc
The entry `compilerPath` is now considered when parsing `c_cpp_properties.json`. If absent, the clang compiler is assumed. Fixes #812.
Detect implicit C/C++ preprocessor defines. Fixes #814.
=> The entry "compilerPath" is now considered when parsing "c_cpp_properties.json"

src/message_handler.cc, src/message_handler.h
This allows clients to e.g. color references differently from
declarations.
=> Include symbol role information in semantic highlighting (fxes #787)
